apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: spring-microservices-poc
build:
  artifacts:
    - image: gressier/osp-config-service
      context: meta-services/osp-config-service
      custom:
        buildCommand: ../../gradlew bootBuildImage --imageName "$IMAGE"

    - image: gressier/osp-license-service
      context: services/osp-license-service
      custom:
        buildCommand: ../../gradlew bootBuildImage --imageName "$IMAGE"

deploy:
  kubectl:
    manifests:
      - k8s/osp-config-service.yaml
      - k8s/osp-license-service.yaml