apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: spring-microservices-poc

build:
  artifacts:
    - image: gressier/osp-config-service
      custom:
        buildCommand: ./gradlew meta-services:osp-config-service:bootBuildImage --imageName "$IMAGE"

    - image: gressier/osp-eureka-service
      custom:
        buildCommand: ./gradlew meta-services:osp-config-service:bootBuildImage --imageName "$IMAGE"


    - image: gressier/osp-license-service
      custom:
        buildCommand: ./gradlew services:osp-license-service:bootBuildImage --imageName "$IMAGE"

    - image: gressier/osp-organization-service
      custom:
        buildCommand: ./gradlew services:osp-organization-service:bootBuildImage --imageName "$IMAGE"

deploy:
  kubectl:
    manifests:
      - '*/**/manifests.yaml'