spring:
  application:
    name: eureka-service
eureka:
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate.on-profile: local
    import: optional:configserver:http://localhost:8888
server:
  port: 8761
logging:
  exception-conversion-word: '%rootException'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

---
spring:
  config:
    activate.on-profile: k8s
    import: configserver:http://osp-config-service
  main.banner-mode: off
server:
  port: 80
logging:
  pattern:
    console: "%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX, UTC} %relative %level ${PID} --- [%thread] %logger : %message%n%rootException"
eureka:
  client:
    service-url:
      defaultZone: http://osp-eureka-service/eureka/

---
spring:
  config:
    activate.on-profile: dev
logging:
  level:
    root: info
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 5
  client:
    register-with-eureka: false
    fetch-registry: false