spring:
  application:
    name: organization-service
eureka:
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate.on-profile: local
    import: optional:configserver:http://localhost:8888
server:
  port: 8081
logging:
  exception-conversion-word: '%rootException'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate.on-profile: k8s
    import: configserver:http://osp-config-service
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://postgresql:5432/osp_organization_service
    username: osp_organization_service
    password: osp_organization_service
  cloud:
    stream:
      bindings:
        output:
          destination: organization-change-topic
          content-type: application/json
      kafka:
        binder:
          brokers: kafka
server:
  port: 80
logging:
  pattern:
    console: "%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX, UTC} %relative %level ${PID} --- [%thread] %logger : %message%n%rootException"
eureka:
  client:
    service-url:
      defaultZone: http://osp-eureka-service/eureka
keycloak:
  auth-server-url: http://keycloak/auth
  realm: osp
  resource: osp-web-app
  credentials:
    secret: 6cb2eb99-c7b1-445b-a0f8-d8b058d15bec
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true

---
spring:
  config:
    activate.on-profile: dev
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    dev.gressier.osp: debug
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'