spring:
  application:
    name: config-service

---
spring:
  config:
    activate.on-profile: local
server:
  port: 8888
logging:
  exception-conversion-word: '%rootException'

---
spring:
  config:
    activate.on-profile: k8s
  main.banner-mode: off
server:
  port: 80

---
spring:
  config:
    activate.on-profile: dev
  profiles:
    include:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
logging:
  level:
    root: info
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'