spring:
  application:
    name: config-service
  profiles:
    active:
      - default
      - native
  main.banner-mode: off
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 80

logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  config:
    activate.on-profile: default
  main.banner-mode: console
server:
  port: 8888