spring:
  application:
    name: config-service
  profiles:
    active:
      - default
      - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  output.ansi.enabled: always
server:
  port: 80

---
spring:
  config:
    activate.on-profile: default
server:
  port: 8888