spring:
  application:
    name: license-service

---
spring:
  config:
    activate.on-profile: local
    import: optional:configserver:http://localhost:8888
server:
  port: 8081
logging:
  exception-conversion-word: '%rootException'

---
spring:
  config:
    activate.on-profile: k8s
    import: configserver:http://osp-config-service
  main.banner-mode: off
server:
  port: 80

---
spring:
  config:
    activate.on-profile: dev
logging:
  level:
    root: info
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'