spring:
  application:
    name: license-service
eureka:
  instance:
    prefer-ip-address: true
resilience4j:
  bulkhead:
    instances:
      getOrganization:
        maxConcurrentCalls: 150
        maxWaitDuration: 500ms
  ratelimiter:
    instances:
      getOrganization:
        limitRefreshPeriod: 1ms
        limitForPeriod: 10
        timeoutDuration: 25ms
  circuitbreaker:
    instances:
      getOrganization:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        ringBufferSizeInHalfOpenState: 3
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
  retry:
    instances:
      getOrganization:
        maxRetryAttempts: 5
        waitDuration: 1s
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException

---
spring:
  config:
    activate.on-profile: local
    import: optional:configserver:http://localhost:8888
server:
  port: 8082
logging:
  exception-conversion-word: '%rootException'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate.on-profile: k8s
    import: configserver:http://osp-config-service
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://postgresql:5432/osp_license_service
    username: osp_license_service
    password: osp_license_service
  cloud:
    stream:
      bindings:
        input:
          destination: organization-change-topic
          content-type: application/json
          group: license-service
      kafka:
        binder:
          brokers: kafka
server:
  port: 80
logging:
  pattern:
    console: "%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX, UTC} %relative %level ${PID} --- [%thread] %logger : %message%n%rootException"
eureka:
  client:
    service-url:
      defaultZone: http://osp-eureka-service/eureka
keycloak:
  auth-server-url: http://keycloak/auth
  realm: osp
  resource: osp-web-app
  credentials:
    secret: 73819b12-1b0a-40b2-a621-e1d0d8d9a7b6
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true

---
spring:
  config:
    activate.on-profile: dev
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    dev.gressier.osp: debug
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    ratelimiters:
      enabled: true
    circuitbreakers:
      enabled: true