spring:
  application:
    name: license-service
  main.banner-mode: off
server:
  port: 80

---
spring:
  config:
    activate.on-profile: default
    import: optional:configserver:http://localhost:8888
  main.banner-mode: console
server:
  port: 8081

---
spring:
  config:
    activate.on-profile: dev
    import: configserver:http://osp-config-service