apiVersion: apps/v1
kind: Deployment
metadata:
  name: osp-config-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: osp-config-service
  template:
    metadata:
      labels:
        app: osp-config-service
    spec:
      containers:
        - name: osp-config-service
          image: gressier/osp-config-service
          ports:
            - containerPort: 80
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev,native
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: http
#            initialDelaySeconds: 10
#            periodSeconds: 3
#            timeoutSeconds: 2
#            failureThreshold: 1
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: http
#            initialDelaySeconds: 20
#            periodSeconds: 8
#            timeoutSeconds: 2
#            failureThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: osp-config-service
spec:
  selector:
    app: osp-config-service
  ports:
    - name: http
      port: 80
      targetPort: 80