apiVersion: apps/v1
kind: Deployment
metadata:
  name: osp-gateway-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: osp-gateway-service
  template:
    metadata:
      labels:
        app: osp-gateway-service
      annotations:
        fluentbit.io/parser: osp-spring-boot
    spec:
      containers:
        - name: osp-gateway-service
          image: gressier/osp-gateway-service
          ports:
            - containerPort: 80
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s,dev
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: http
#            initialDelaySeconds: 10
#            periodSeconds: 3
#            timeoutSeconds: 2
#            failureThreshold: 1
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: http
#            initialDelaySeconds: 20
#            periodSeconds: 8
#            timeoutSeconds: 2
#            failureThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: osp-gateway-service
spec:
  selector:
    app: osp-gateway-service
  ports:
    - name: http
      port: 80
      targetPort: 80