apiVersion: apps/v1
kind: Deployment
metadata:
  name: osp-organization-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: osp-organization-service
  template:
    metadata:
      labels:
        app: osp-organization-service
      annotations:
        fluentbit.io/parser: osp-spring-boot
    spec:
      containers:
        - name: osp-organization-service
          image: gressier/osp-organization-service
          ports:
            - containerPort: 80
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s,dev

---
apiVersion: v1
kind: Service
metadata:
  name: osp-organization-service
spec:
  selector:
    app: osp-organization-service
  ports:
    - name: http
      port: 80
      targetPort: 80