apiVersion: apps/v1
kind: Deployment
metadata:
  name: osp-license-service
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: osp-license-service
  template:
    metadata:
      labels:
        app: osp-license-service
    spec:
      initContainers:
        - name: wait-for-200
          image: stefanevinance/wait-for-200
          env:
            - name: URL
              value: osp-config-service/actuator/health
      containers:
        - name: osp-license-service
          image: gressier/osp-license-service
          ports:
            - containerPort: 80
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 8
            timeoutSeconds: 2
            failureThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: osp-license-service
spec:
  selector:
    app: osp-license-service
  ports:
    - port: 80
      targetPort: 80