###
POST {{licenseService}}/organizations/{{organizationId}}/licenses
Content-Type: application/json

{
  "productName": "Adobe Illustrator",
  "description": "Industry-leading vector graphics software",
  "type": "STANDARD"
}
> {% client.global.set("licenseId", response.body.id) %}

###
GET {{licenseService}}/organizations/{{organizationId}}/licenses
Accept: application/json

###
GET {{licenseService}}/organizations/{{organizationId}}/licenses/{{licenseId}}
Accept: application/json

###
PUT {{licenseService}}/organizations/{{organizationId}}/licenses/{{licenseId}}
Content-Type: application/json

{
  "productName": "Illustrator",
  "description": "A vector graphics editor and design program",
  "type": "STANDARD"
}

###
DELETE {{licenseService}}/organizations/{{organizationId}}/licenses/{{licenseId}}